name: riffwizard
channels:
  - conda-forge
dependencies:
  - _openmp_mutex=4.5
  - blinker=1.9.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - certifi=2025.8.3
  - cffi=2.0.0
  - charset-normalizer=3.4.3
  - click=8.3.0
  - cpython=3.13.7
  - dash=3.2.0
  - filelock=3.19.1
  - flask=3.1.2
  - fsspec=2025.9.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - idna=3.10
  - importlib-metadata=8.7.0
  - itsdangerous=2.2.0
  - jinja2=3.1.6
  - libabseil=20250512.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcxx=21.1.2
  - libexpat=2.7.1
  - libffi=3.4.6
  - libhwloc=2.12.1
  - libiconv=1.18
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libprotobuf=6.31.1
  - libsqlite=3.50.4
  - libtorch=2.8.0
  - libuv=1.51.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libzlib=1.3.1
  - llvm-openmp=21.1.0
  - markupsafe=3.0.2
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - narwhals=2.5.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - numpy=2.3.3
  - openssl=3.5.3
  - optree=0.17.0
  - packaging=25.0
  - pandas=2.3.2
  - pip=25.2
  - plotly=6.3.0
  - pybind11=2.13.6
  - pybind11-abi=4
  - pybind11-global=2.13.6
  - pycparser=2.22
  - pysocks=1.7.1
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytorch=2.8.0
  - pytz=2025.2
  - readline=8.2
  - requests=2.32.5
  - retrying=1.4.2
  - setuptools=80.9.0
  - six=1.17.0
  - sleef=3.9.0
  - sympy=1.14.0
  - tbb=2021.13.0
  - tk=8.6.13
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - urllib3=2.5.0
  - werkzeug=3.1.3
  - zipp=3.23.0
  - zstandard=0.25.0
  - zstd=1.5.7
